integralfamilies:
- name: "topo1"
  loop_momenta: [k1,k2]
  top_level_sectors: [63]
  propagators:
  - ["k1",0]
  - ["k2",0]
  - ["k1+k2",0]
  - ["k2+p3",0]
  - ["k1 + k2 + p3", 0]
  - {bilinear: [["p1","k1"],0]}
  - {bilinear: [["p2","k1"],0]}
  - {bilinear: [["p1","k2"],0]}
  - {bilinear: [["p2","k2+p3"],0]}
